import { AppBar, Toolbar, Typography, Container } from '@mui/material';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: '3D Image Processing',
  description: 'Generated by create next app',
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <AppBar position="static">
          <Toolbar sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <Typography variant="h6">Advanced 3D Image Processing App</Typography>
              <Link href='/' style={{ textDecoration: 'none', color: 'white' }}>
                Home
              </Link>
              <Link href='/register' style={{ textDecoration: 'none', color: 'white' }}>
                Register
              </Link>
              <Link href='/dashboard' style={{ textDecoration: 'none', color: 'white' }}>
                Dashbaord
              </Link>

            </Toolbar>
            </AppBar>
          <Container>
            {children}
          </Container>
        </div>
      </body>
    </html>
  );
}
