import React from "react";

export const metadata = {
  title: "3D-Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <div className="">
      <div className="">
        <div className="">      
        </div>
        <div className="">{children}</div>
      </div>
    </div>
  );
}
